#!/bin/sh #############################################################
#                                                           #
#  Contents of file Copyright (c) Moogsoft Inc 2010         #
#                                                           #
#-----------------------------------------------------------#
#                                                           #
#  WARNING:													#
#  THIS FILE CONTAINS UNPUBLISHED PROPRIETARY				#
#  SOURCE CODE WHICH IS THE PROPERTY OF MOOGSOFT INC AND	#
#  WHOLLY OWNED SUBSIDIARY COMPANIES.						#
#  PLEASE READ THE FOLLOWING AND TAKE CAREFUL NOTE:			#
#															#
#  This source code is confidential and any person who		#
#  receives a copy of it, or believes that they are viewing	#
#  it without permission is asked to notify Phil Tee		#
#  on 07734 591962 or email to phil@moogsoft.com.			#
#  All intellectual property rights in this source code		#
#  are owned by Moogsoft Inc.  No part of this source code 	#
#  may be reproduced, adapted or transmitted in any form or	#
#  by any means, electronic, mechanical, photocopying,		#
#  recording or otherwise.									#
#															*
#  You have been warned....so be good for goodness sake...	#
# 															#
#############################################################
JAVA="java -jar"
JSCOMP="$JAVA $MOOGSOFT_COTS_HOME/packages/compiler.jar"
output_file=""
srcs=""
command_line=""
while [ "$*" != "" ]
do
  if [ "$1" = "-o" ]
  then
     shift
     output_file=$1
     shift
     shift
  fi
  if [ "$1" != "" ]
  then
    srcs="$srcs --js $1 "
  fi
  shift
done

command_line="$JSCOMP $srcs --js_output_file $output_file"
`$command_line`
